export const texts = {
  "ja": {
  "topMainVisualSub": "確かな技術力をもって、挑戦し続ける",
    "topNewsSub": "ニュース",
    "Button_A": "もっとみる",
    "Button_B": "さらに詳しく",
    "topWorksSub": "佐竹の事業",
    "topWorksHeadline": "佐竹製作所はこれからの未来を創造する<br>グローバルカンパニーです。",
    "topWorksBody": "佐竹製作所グループは金属部品加工で培った独自の技術と提案力を核とした次世代ソリューションカンパニーです。<br>お客さまのニーズにお応えし、革新的な技術提案を続けてまいります。触覚センサを活用した佐竹ブランド商品開発や、少子化社会に役立つロボティクスの設計開発、顧客に提案ができる技術商社として“佐竹ブランド”の価値を高めていきます。",
    "topWorksMetalHeadline": "金属加工事業",
    "topWorksMetalBody": "試作品から量産品までカスタムメイドでお応えします。精密部品加工技術をベースに国内・海外の独自のネットワークを活用して、カスタムメイドの部品加工を手がけています。<br>多品種・小ロット、試作品から量産品まで、お客さまが真に求めている付加価値を創造し提供します。",
    "topWorksFAHeadline": "FA事業",
    "topWorksFABody": "ロボットシステムによる生産性向上と顧客に提案できるサービスを追加する『FAロボット化』を提案できる企業を目指します。<br>人不足に対応した省人化・自動化を提案できる技術商社を目指します。",
    "topWorksFittHeadline": "継手事業",
    "topWorksFittBody": "世界トップクラスの継手ブランドJSKを開発・製造し、安定供給と即納体制を実現しております。<br>半導体装置向け特殊ガス用継手としてトップクラスの品質を誇る佐竹製作所グループの三興工業（株）の継手・ガスケット事業をクリーンルームを備えた自社工場で開発、製造しています。",
    "topWorksSensorHeadline": "センサ事業",
    "topWorksSensorBody": "ロボットと人間のインターフェースを進化させる革新的な触覚センサの開発・製造・販売しています。<br>東京大学と連携してオリジナルのセンサを開発。その後センサ事業を分社化して設立されたタッチエンス株式会社(関連会社)は、経験豊富なエンジニアがお客様の新製品開発をサポートします。",
    "topAboutSub": "会社情報",
    "topAboutHeadline": "多様なニーズにお応えし、確かな品質と<br>世界のモノづくりを支える会社です。",
    "topAboutBody": "常にお客様に寄り添いながら、佐竹にしかないソリューションを提供します。<br>佐竹グループは確かな品質の自社工場と幅広い協力メーカー網で、ベストなコーディネイトと万全なサポートを約束いたします。",
    "topAboutMessageTitle": "代表メッセージ",
    "topAboutMessageBody": "産業構造の変化とモノづくりの進化に合わせ、次世代に役立つ事業を創造していきます。",
    "topAboutNetworkTitle": "グローバル<br class='pc-only'/>ネットワーク",
    "topAboutNetworkBody": "FAロボットシステムインテグレータとして、佐竹ブランドの装置販売するための布石を打ちます。<br class='pc-only'/>自動化・ロボット化する装置を設計開発できる機能を保有します。",
    "": "",
    "NewsNext": "次へ",
    "NewsPrev": "戻る",
    "WorksTopTitle": "佐竹の事業",
    "WorksTopHeadline": "佐竹製作所はこれからの<br class='sp-only'/>未来を創造する<br class='sp-only'/>グローバルカンパニーです。",
    "WorksTopBody": "佐竹製作所グループは金属部品加工で培った<br>独自の技術と提案力を核とした次世代<br class='sp-only'/>ソリューションカンパニーです。<br>お客さまのニーズにお応えし、<br class='sp-only'/>革新的な技術提案を続けてまいります。<br>触覚センサを活用した佐竹ブランド商品開発や、<br class='sp-only'/>少子化社会に役立つロボティクスの設計開発、<br>顧客に提案ができる技術商社として<br class='sp-only'/>“佐竹ブランド”の価値を高めていきます。",
    "worksMetalTitle": "金属加工事業",
    "worksMetalBody": "試作品から量産品までカスタムメイドでお応えします。<br class='pc-only'/>精密部品加工技術をベースに国内・海外の独自のネットワークを活用して、カスタムメイドの部品加工を手がけています。<br> 多品種・小ロット、試作品から量産品まで、お客さまが真に求めている付加価値を創造し提供します。",
    "worksFullorderTitle": "カスタム部品の提案・製造・量産",
    "worksFullorderBody": "お客様のどのような要望も形にすることに特化したフルオーダー事業。設計から製品化・品質管理の面までサポートする事業です。",
    "worksSemiorderTitle": "自社工場でのFA部品の製造",
    "worksSemiorderBody": "多品種・小ロット・短納期を突き詰めたFA部品事業。<br class='pc-only'/>速さに特化することにより品質を高める事業です。",
    "worksFATitle": "FA事業",
    "worksFABody": "ロボットシステムによる生産性向上と顧客に提案できるサービスを追加する『FAロボット化』を提案できる企業を目指します。<br>人不足に対応した省人化・自動化を提案できる技術商社を目指します。",
    "worksFittingsTitle": "継手事業",
    "worksFittingsBody": "世界トップクラスの継手ブランドJSKを開発・製造し、安定供給と即納体制を実現しております。<br>半導体装置向け特殊ガス用継手としてトップクラスの品質を誇る佐竹製作所グループの三興工業（株）の継手・ガスケット事業をクリーンルームを備えた自社工場で開発、製造しています。",
    "worksSensorTitle": "センサ事業",
    "worksSensorBody\n": "ロボットと人間のインターフェースを進化させる革新的な触覚センサの開発・製造・販売しています。<br>東京大学と連携してオリジナルのセンサを開発。その後センサ事業を分社化して設立されたタッチエンス株式会社(関連会社)は、経験豊富なエンジニアがお客様の新製品開発をサポートします。",
    "MetalTopTitle": "金属加工事業",
    "MetalTopHeadline": "佐竹の金属加工事業は、<br class='sp-only'/>試作品から量産品まで<br>カスタムメイドでお応えします。",
    "MetalTopBody": "オーダーメイドに特化した「カスタム部品事業」と、<br>セミオーダー化により<br class='sp-only'/>速さに特化した「FA部品事業」の<br class='sp-only'/>2つの事業によって<ps>お客様の多彩なニーズに、<br class='sp-only'/>最適な方法でお答えします。",
    "MetalTopCustomBody": "お客様のどのような要望も形にすることに特化したフルオーダー事業。設計から製品化・品質管理の面までサポートする事業です。",
    "MetalTopFATitle": "FA部品事業",
    "MetalTopFABody": "多品種・小ロット・短納期を突き詰めたFA部品事業。速さに特化することにより品質を高めるFA部品事業です。",
    "CustomTitle": "カスタム部品事業",
    "CustomHeadline": "どんなオーダーにも<br class='sp-only'/>答えます。",
    "CustomBody": "お客さまの要望をかなえるフルオーダーによるカスタム部品開発事業です。<br>最適な製品を提案・製造・量産まで一貫してサポートします。<br>具体的な設計図が決まっているものから、アイデアレベルのものまでまずご相談ください。<br>100社以上の専門メーカーとの協力体制によって、効率を高める改善案から、<br>高度な技術が必要な製品の開発まで幅広くサポートいたします。",
    "C_SatakeQuality01Tilte": "精度の高い製品を作るのは当たり前。<br>それ以上のアイデアを提案いたします。",
    "C_SatakeQuality01Body": "精度の高い技術が必要な製品開発はとても重要ですが、<ps>納期短縮などの効率性も非常に重要です。<br class='pc-only'/>佐竹の長年の経験を生かし、最適な提案をいたします。",
    "C_SatakeQuality02Tilte": "連携メーカーは200社以上。高度な技術にも対応いたします。",
    "C_SatakeQuality02Body": "佐竹は自社工場での技術やノウハウを持ちつつ、<br class='pc-only'/>さらにそれぞれの違った技術を200社以上の専門メーカーと<br class='pc-only'/>協力体制を築いています。<ps>佐竹の提携ネットワークを使った様々なご提案が可能です。",
    "C_SatakeQuality03Tilte": "最新の検査機器やデータベース化。<br>お客さまの信頼に応える品質保証体制。",
    "C_SatakeQuality03Body": "お客さまから受けた様々なオーダーを管理するために、最新の<br class='pc-only'/>検査機器やデータベース化など新しい技術を積極的に<ps>導入し、より良い品質を保つために常に改善されています。",
    "C_SatakeQualityAssurance": "佐竹の品質保証",
    "C_Assurance01Title": "01. バーコードシステムを<br class='sp-only'/>使った全製品のデータベース化",
    "C_Assurance01Body": "佐竹製作所では、独自開発したバーコードを利用したデータベースを利用し、常時3万点以上の金属加工部品の品質管理・出荷管理を行なうとともに、最短1日という超短納期を実現しています。",
    "C_Assurance02Title": "02. 最新の検査機器による徹底チェック",
    "C_Assurance02Body": "佐竹製作所の製品は品質保証部門が中心となって、一般の測定器のほか、最新の各種検査装置により、素材の入荷時から梱包出荷までの各製造工程の検査を行なっています。不良ゼロを目標とした組織的な品質管理で厳しく検査することにより、高い品質が保証されています。",
    "C_Assurance03Title": "03. 品質マネジメントシシステム",
    "C_Assurance03Body": "佐竹製作所は、お客様満足度向上のため品質方針を定め、品質マネジメントの国際規格であるISO9001を全事業所にて認証取得いたしました。 今後も継続的改善を実施し、よりよい製品・サービスの安定と充実を目指してまいります。また品質ISO・環境ISOも取得しました。取得することが目的ではなく、当社のマネジメントシステムを自分のものにして、提供価値を高めることを目的としました。",
    "C_ISO9001": "ISO9001",
    "C_ISO9001Date01": "1997年4月",
    "C_ISO9001Body01": "山形工場 ISO9001認証を取得（JQA-1738）",
    "C_ISO9001Date02": "2003年9月",
    "C_ISO9001Body02": "山形工場 ISO9001:2000移行審査合格",
    "C_ISO9001Date03": "2006年2月",
    "C_ISO9001Body03": "ISO9001 全社拡大認証取得",
    "C_ISO14001": "ISO14001",
    "C_ISO14001Date01": "2006年11月",
    "C_ISO14001Body01": "ISO14001認証取得（JQA-EM5640）",
    "C_ISO9001PDF": "ISO9001登録証・付属書",
    "C_ISO14001PDF": "ISO14001登録証・付属書",
    "C_ExamplesOfProposals": "ご提案事例",
    "C_ExamplesOfProposalsBody": "佐竹製作所が得意とするフルオーダーメイドの金属部品加工は、お客様の課題を積極的に解決してきました。<br class='pc-only'/>「その想いをカタチに・・・」を実現したご提案事例をご紹介します。",
    "C_Examples01Title": "コストダウン化",
    "C_Examples01Body": "お客様に冷間圧造+切削をご提案し、約30％のコストダウンに成功しました。冷間圧造でブランク品を加工することで、大幅に材料費と切削加工費が削減可能です。ある程度の量と軸形状に膨らみがある形状の部品に向いている加工方法です。",
    "C_Examples02Title": "設計",
    "C_Examples02Body": "切削プレートと圧入ピンの組み合わせでは、最適な圧入ピンのサイズを独自設計してご提案し、完成品に仕上げました。製品の試作用のラフ図面やポンチ絵の段階からでも品質、納期、コストをお客さまと一緒に考え、製造設計をサポートし、設計リードタイムを大幅に短縮致します。",
    "C_Examples03Title": "難形状加工",
    "C_Examples03Body": "既存の技術では困難な大きなロスが出る加工を、最適な溶接技術をもつ協力工場と連携し、ワンストップでご提供致しました。また、完成品は表面がセンシティブであった為、キズのつかない梱包も設計し、ご提案しました。",
    "C_Examples04Title": "へら絞り加工",
    "C_Examples04Body": "試作から量産への移行をスムーズに進めたいお客様にプレス加工品の試作としてへら絞りをご提案いたしました。へら絞りは１個から注文可能で、プレス加工では金型のコストが心配な小ロットのスポット品などに最適です。",
    "C_Examples05Title": "ワイヤーカット加工",
    "C_Examples05Body": "専門メーカーと連携し、ワイヤーカット機12台以上を毎日20時間前後稼働させ、時間当りの大幅なコストダウンを実現しています。板厚0,01～300mmまで対応でき、薄物であれば重ねて加工が可能です。特殊形状も含め約250種類の治具を完備しコストダウン化しています。",
    "C_Examples06Title": "ロストワックス加工",
    "C_Examples06Body": "佐竹製作所のロストワックスは「海外生産で国産品より安く、国産品と同品質」で、ご提供できます。国内で生産した場合と比較して材料代で約マイナス30％、型代は約マイナス65%と大幅に削減することが可能です。",
    "C_Examples07Title": "順送プレス加工",
    "C_Examples07Body": "単発プレス＋ASSYの複数工程から、一体化プレスへの技術等により、お客様のニーズに合ったご提案をいたします。大型の順送プレス機は、ステンレス板厚t9.0mmまで加工ができ約30％のコストダウンとリードタイムの短縮が可能です。",
    "FAComponentDivisionTitle": "FA部品事業",
    "FAComponentDivisionHeadline": "もっと早く。<br class='sp-only'/>業界最速を目指して。",
    "FAComponentDivisionBody": "FA部品事業は自社工場での一貫生産方式を取り入れ、<br class='pc-only'/>スピードアップとコスト削減を目指しています。今よりもさらに早くお客様に製品を届けるにはどうしたら良いか。日々考えています。<br>工場の24時間稼働、労働環境の改善、現場でのアイデアによる改善などの積み重ね。<br>結果、注文を受けてから最短４時間後には出荷を実現しています。<br class='pc-only'/>これからもさらに早くすべく改善を続けていきます。",
    "F_SatakeQuality01Tilte": "数多くの加工を施しても<br>納期は変わりません。",
    "F_SatakeQuality01Body": "切削・プレス旋盤・熱処理・表面処理などの加工を<br>施しても納期は変わりません。<br class='pc-only'/>サイズ違いなどの30000種類以上の部品に対応可能です。",
    "F_SatakeQuality02Tilte": "「超小ロット」の実現。<br>ネジ１本でも即日配送いたします。",
    "F_SatakeQuality02Body": "ネジ１本でも他の注文と同じように、即日配送という「超小ロット」を実現しています。<br>もちろん大量の注文数も即日配送可能です。",
    "F_SatakeQuality03Tilte": "超短納期を実現するために、<br>24時間365日、改善を重ねています。",
    "F_SatakeQuality03Body": "超短納期を実現するために、もっと早く届けるために改善を重ねています。24時間稼動、最新の設備の導入、労働環境の改善、現場からのアイデアによる改善など。様々な小さな改善を積み重ねて、短納期を実現しています。",
    "F_FourHoursTitle": "注文から出荷まで、最短4時間！",
    "F_ProcessTitle": "多彩な加工技術例",
    "F_Process01Title": "旋盤",
    "F_Process01Body": "40台のNC旋盤を使って、多品種の製造に対して段取り時間を最小化しています。",
    "F_Process02Title": "熱処理",
    "F_Process02Body": "小ロット・短納期を実現するため熱処理時間の短いソルトバスを自社工場内に導入しています。",
    "F_Process03Title": "研磨",
    "F_Process03Body": "外形公差をミクロン単位に抑えることが可能な円筒研磨です。面粗さは0.8a以下に抑えます。",
    "F_Process04Title": "マシニングセンター",
    "F_Process04Body": "縦型・横型両方を完備し平面的、立体的ワークを短時間で行なうことが可能です。",
    "F_Process05Title": "溶接",
    "F_Process05Body": "TIG溶接機を複数台完備し、多品種、短納期の加工に対応しています。",
    "F_Process06Title": "表面処理",
    "F_Process06Body": "表面処理は無電解Ni、酸化クロメート、亜鉛鍍金などの専用槽を保有しています。",
    "F_Process07Title": "三次元測定機",
    "F_Process07Body": "AI機能を搭載した、高精度の三次元測定機で品質管理しています。",
    "F_Process08Title": "データベース化",
    "F_Process08Body": "データベース化により約3万点のセミオーダーメイド製品を1個流しで対応しています。",
    "F_Process09Title": "成分分析",
    "F_Process09Body": "金属材料の材質が仕様と合っているか、さらに、環境規制物質は規制値以下かを分析しています。",
    "FABusinessTitle": "FA事業",
    "FABusinessHeadline": "次世代に役立つ<br class='sp-only'/>FAシステムインテグレータ<br class='sp-only'/>として<br class='pc-only'/>自社FAシステムを<br class='sp-only'/>開発します。",
    "FABusinessBody": "中小企業にとって生産性向上は重要な経営課題の一つであり、<br class='pc-only'/>佐竹製作所は省人化・自動化による生産性向上を提案できる技術会社を目指しています。<br>部品製作から始まった佐竹製作所は、よりよいモノづくり会社を目指して中小企業ならではの、コストパフォーマンスに優れたFAシステムの開発にも取り組んでいます。<br>自社工場に導入して効率化を図るだけでなく、実践を通じて検証・改善を図り、 システムの進化を続けます。その先のスマート工場に関わるFAシステムの製品化、 販売を目指してモノづくり業界がさらに進化していけるよう、開発を進めていきます。",
    "FABusinessButtonLabel": "佐竹の新しいFAページへ",
    "FABusinessAboutTitle": "佐竹製作所のFA事業について",
    "FABusinessAbout01Title": "部品製造",
    "FABusinessAbout01Body": "FA事業は、自社工場の現場を分析し、IoTやロボット、RPAなどの技術を用いて省人化・自動化の導入を推進しています。現場に最適なソリューションを提供します。",
    "FABusinessAbout02Title": "FA装置の開発",
    "FABusinessAbout02Body": "自社工場を運営するMI事業は、提供されたソリューションを活用します。運用実績から得られる現場の声をFA事業へフィードバックし、FA事業が一体となって効率向上を目指します。",
    "FABusinessAbout03Title": "FA装置の販売",
    "FABusinessAbout03Body": "実績を積み重ねたソリューションはモノづくり工場の現場に適した機能を装備。ソリューションの提案により、スマート工場への革新をスタートからサポートします。",
    "FABusinessFutureTitle": "FA事業によって広がる、<br class='sp-only'/>佐竹製作所の未来",
    "FABusinessFuture01Title": "顧客の「多様なニーズ」に<br class='sp-only'/>お応えします。",
    "FABusinessFuture02Headline": "既存事業の拡大",
    "FABusinessFuture02Body": "・幅広い製品の供給<br>・モジュール化への対応",
    "FABusinessFuture03Headline": "多様なソリューションの提供",
    "FABusinessFuture03Body": "・FA装置のカスタマイゼーション<br>・高機能センサ実装グリッパー<br>・スマートプラットフォーム",
    "FABusinessFuture04Title": "次世代の成長分野に参入し、<br>事業を広げていきます。",
    "FABusinessFuture05Headline": "IoT技術開発",
    "FABusinessFuture05Body": "・IoTの基本モジュールとアプリケーション<br>・センシング技術（機械・モノ・人の動き）",
    "FABusinessFuture06Headline": "自動化、省力化機器との融合",
    "FABusinessFuture06Body": "・RPAによる自動化、省力化機器開発",
    "FABusinessFuture07Headline": "自動化製造ラインの多様化するニーズに対応",
    "FABusinessFuture07Body": "・可視化、監視、工程分析",
    "FittingBusinessTitle": "継手事業",
    "FittingBusinessHeadline": "三興工業は、超高純度ガス・<br class='sp-only'/>ケミカル・極高真空用の<br>継手専業メーカーです。",
    "FittingBusinessBody": "三興工業は、25年以上培われ蓄積された<br>ウルトラクリーンテクノロジー技術を生かした、<br class='sp-only'/>超高純度ガス・ケミカル・極高真空用の<br>継手専業メーカーです。画期的な新構造の継手として、<br class='pc-only'/>世界各国で特許を取得しています。",
    "FittingBusinessContact": "三興工業のお問い合わせ先",
    "FittingBusinessNumber": "03-3526-2860",
    "FittingBusinessAdrress": "受付時間 / 平日9:00 - 18:00 （土日祝日を除く）<br class='sp-only'/>FAX / 03-3525-8059<br class='sp-only'/>メール / kanrika@jsk-sanko.co.jp",
    "FittingBusinessButton": "三興工業のホームページへ",
    "SensorBusinessTitle": "センサ事業（関連会社）",
    "SensorBusinessHeadline": "タッチエンス(関連会社)は「触覚」の未来を科学する<br class='pc-only'/>センサカンパニーです。",
    "SensorBusinessBody": "新規性の高いオリジナル触覚センサや<br class='sp-only'/>センサモジュールは、<br>民生ロボット・スポーツ器具・介護機器などの<br class='sp-only'/>市場で<br class='pc-only'/>高く評価され、<br class='sp-only'/>これまでにない入力デバイスや検知デバイスの<br class='sp-only'/>実現に貢献しています。",
    "SensorBusinessContact": "タッチエンスのお問い合わせ先",
    "SensorBusinessNumber": "03-3847-9551",
    "SensorBusinessAdrress": "受付時間 / 平日9:00 - 18:00 （土日祝日を除く）<br class='sp-only'/>FAX / 03-3847-9552<br class='sp-only'/>メール / info@touhchence.jp",
    "SensorBusinessButton": "タッチエンスのホームページへ",
    "AboutTopTitle": "会社情報",
    "AboutTopHeadline": "多様なニーズにお応えし、<br>確かな品質と世界のモノづくりを<br class='sp-only'/>支える会社です。",
    "AboutTopBody": "常にお客様に寄り添いながら、<br class='sp-only'/>佐竹にしかないソリューションを提供します。<br>佐竹グループは確かな品質の自社工場と<br class='sp-only'/>幅広い協力メーカー網で、<br>ベストなコーディネイトと万全なサポートを<br class='sp-only'/>約束いたします。",
    "AboutTop01Title": "代表メッセージ",
    "AboutTop01Body": "代表の尾方謙一から<br>皆様へのメッセージです。",
    "AboutTop02Title": "佐竹について",
    "AboutTop02Body": "経営理念、経営方針を<br class='pc-only'/>お伝えします。",
    "AboutTop03Title": "グローバルネットワーク",
    "AboutTop03Body": "海外の協力会社を<br class='pc-only'/>ご紹介します。",
    "AboutTop04Title": "事業所・アクセス",
    "AboutTop04Body": "弊社へのアクセス情報を<br class='pc-only'/>お伝えします。",
    "AboutTop05Title": "沿革",
    "AboutTop05Body": "これまでの佐竹の歩みを<br class='pc-only'/>ご紹介します。",
    "AboutTop06Title": "企業概要",
    "AboutTop06Body": "佐竹の基本的な情報を<br class='pc-only'/>お伝えします。",
    "AboutCEOMessageHeadTitle": "代表メッセージ",
    "AboutCEOMessageTitle": "代表取締役社長<br>尾方 謙一",
    "AboutCEOMessageBody01": "当社は昭和12年から、お客様のニーズにあった<br class='sp-only'/>特殊ボルト・機械部品など<br>多品種・小ロット・短納期で提供してまいりました。",
    "AboutCEOMessageBody02": "金属部品を提供してきた当社が、<br class='sp-only'/>これから激変する産業構造に対応できるよう、<br>あらゆる挑戦を続け、成長・進化していくことで、<br>さらにお客様のニーズにお応えすることを<br class='sp-only'/>大切にしております。",
    "AboutCEOMessageBody03": "「独自技術とサービスを提案する<br class='sp-only'/>次世代ソリューションカンパニー」",
    "AboutCEOMessageBody04": "私たちは、これまで特殊な金属部品を<br class='sp-only'/>提供してきた経験を生かし、市場の進化に合わせて、<br>それぞれの事業を進化させることが<br class='sp-only'/>お客様ニーズに対応することだと考えております。",
    "AboutCEOMessageBody05": "リーマンショック以降、日本の産業構造が激変する中、非成長事業をやめ、<br class='pc-only'/>金属部品のオーダーメイド事業を集約し、新たなサービスの拡充を実現。<br>既存工場をスピードに特化させてFA部品事業を<br class='sp-only'/>強化し、<br class='pc-only'/>新事業を立ち上げる機能として<br class='sp-only'/>事業開発部を設置しました。<br class='pc-only'/>その事業開発部がFA市場の次（民生ロボット）を狙い、センサ事業部を創り、<br class='pc-only'/>さらに既存事業部とのシナジーとして自社オリジナル金属部品を創り、<br class='pc-only'/>次の市場に送り込む・・・というように常に前に進む会社です。",
    "AboutCEOMessageBody06": "現在では佐竹グループも3社となり、<br>オンリーワン技術として世界初の触覚センサを<br class='sp-only'/>提供するセンサ事業（タッチエンス（関連会社））、<br>特殊継手メーカーのJSK事業（三興工業）の<br class='sp-only'/>自社開発のブランドも加わり、<br class='pc-only'/>樹脂添加剤、ガスセンサ<br class='sp-only'/>など他社ブランド製品の取扱いも拡大中で、<br>お客様に提供できるラインアップも充実しました。",
    "AboutCEOMessageBody07": "また、中国やタイをはじめアジアを中心とした<br class='sp-only'/>海外事業所も拡充しており、<br class='pc-only'/>提供エリアを徐々に<br class='sp-only'/>拡大させて、世界の生産設備産業に<br class='sp-only'/>貢献できるよう努めてまいります。",
    "AboutCEOMessageBody08": "オーダーメイドの金属加工事業も、これまで以上に<br class='sp-only'/>お客様のニーズに合わせ、<br class='pc-only'/>新しい付加価値で<br class='sp-only'/>提案できるよう進化を続けてまいります。",
    "AboutCEOMessageBody09": "当社は若い経営層と若い従業員で、更に<br class='sp-only'/>あらゆる挑戦を続けて、<br class='pc-only'/>お客様のために<br class='sp-only'/>成長・進化していきますのでご期待下さい。",
    "AboutSatakeTitle": "佐竹について",
    "AboutSatakeHeadline01": "新規分野に挑戦し、<br class='sp-only'/>成長できる会社です。",
    "AboutSatakeBody01": "私たちは金属部品加工を中心とした<br class='sp-only'/>精密機械部品のサポーティングインダストリー<br class='sp-only'/>として、<br class='pc-only'/>お客様のニーズにお応えしています。<br class='sp-only'/>世の中で一番ではなく、<br class='pc-only'/>「お客様の中で一番」の<br class='sp-only'/>パートナーを目指して成長し、<br class='sp-only'/>進化を続けています。",
    "AboutSatakeHeadline02": "成長と展開を続ける佐竹の事業",
    "AboutSatakeProjectTitle": "プロジェクト開発",
    "AboutSatakeProjectBody": "既存事業の強化・成長・進化を支援するとともに新規プロジェクトを開発、軌道に乗せ事業化します。事業の企画・立案・立ち上げ・ブランド戦略を行い確実な展開を支援します。<br>グローバル化する各事業の積極的な海外展開やクロスライセンス化を図ります。海外事業所の運営を行うとともに現地調達化を推進しています。",
    "AboutSatakeSupportTitle": "既存事業の<br>強化・成長・進化を支援",
    "AboutSatakeSupportBody": "市場の進化に合わせてそれぞれの事業を進化させることで、お客様のニーズに的確に答えていきます。",
    "AboutSatakeNewTitle": "新規事業の企画・立案・<br>ブランド戦略を行う",
    "AboutSatakeNewBody": "変化し続ける産業業界に対応できるよう、新しい事業の開拓にも日々チャレンジしています。",
    "AboutSatakeOverseasTitle": "事業の海外展開、<br>クロスライセンス化を図る",
    "AboutSatakeOverseasBody": "アジアを中心とした海外事業所も拡大しながら、お客様に提供できる製品ラインナップを充実させています。",
    "AboutSatakeManaHeadline": "経営目的",
    "AboutSatakeManaBoby01": "1. 顧客の満足度を高め価値ある存在となる。",
    "AboutSatakeManaBoby02": "2. 社員に生活向上と自己実現の<br class='sp-only'/>チャンスを与える。",
    "AboutSatakeManaBoby03": "3. わが社を維持発展させ社会に貢献する。",
    "AboutSatakeBasicHeadline": "経営基本方針",
    "AboutSatakeBasicBody": "わが社は産業発展と次世代社会の生活向上に寄与するため、一人ひとりが自らを高めて、\n<br>提供価値の進化を続けることで、お客様にとってNo.1のパートナーになる。",
    "AboutSatakePerHeadline": "行動指針",
    "AboutSatakePerBody01": "1. 開発と革新、改善に積極的にチャレンジし、やりがいのある強い企業にしよう。",
    "AboutSatakePerBody02": "2. 顧客には誠意をもってスピーディに<br class='sp-only'/>対応しよう。",
    "AboutSatakePerBody03": "3. 品質に徹底して、こだわった仕事をしよう。",
    "AboutSatakePerBody04": "4. 現場、現物、現実の3現主義で<br class='sp-only'/>問題の解決にあたろう。",
    "AboutSatakePerBody05": "5. 実践と自己啓発により、<br class='sp-only'/>優れたプロになろう。",
    "AboutSatakeFutureHeadline": "未来志向",
    "AboutSatakeFutureBody": "創造し進化する社会。時代が変われば産業構造や価値観が変わります。その変化の中で常に先を見通し、新しい時代に合わせた変革と体制づくりで柔軟に対応。新分野、新領域の開拓に果敢にチャレンジし続けます。",
    "AboutSatakeDeveHeadline": "開発志向",
    "AboutSatakeDeveBody": "産学連携でオンリーワンを。 精密加工分野に止まらず、東京大学と産学連携してロボットの認識・制御技術分野に進出するなど、常に新しい技術との融合により技術開発のスピードをアップ。オンリーワンの製品づくりに挑戦しています。",
    "AboutSatakeCusHeadline": "顧客志向",
    "AboutSatakeCusBody": "日本一のサービスをめざす。私たちがお届けするのはサービスの究極。ネジ1本のご注文もお受けし、即日出荷もOK。多品種・小ロット・短納期を徹底追求したサービス体制を整え、お客様にとってベストのパートナーをめざします。",
    "AboutGlobalTitle": "グローバルネットワーク",
    "AboutGlobalHeadline": "多様な海外ネットワークの強み",
    "AboutGlobalBody": "世界各国に展開している拠点と連携し、<br class='sp-only'/>グローバルなサポートを実現します。<br>私たちは金属部品加工を中心とした<br class='sp-only'/>精密機械部品のサポーティングインダストリー<br>として、お客様のニーズにお応えしています。<br class='sp-only'/>世の中で一番ではなく、<br class='pc-only'/>「お客様の中で一番」の<br class='sp-only'/>パートナーを目指して成長し、<br class='sp-only'/>進化を続けています。",
    "AboutGlobalSHANGHAI": "上海宗雄貿易有限公司",
    "AboutGlobalSHANGHAIBody01": "中国の営業・販売拠点を展開世界最大のFAロボット市場に狙いを定め、<br class='pc-only'/>新たな上海拠点を活用して、業務範囲を拡大していきます。",
    "AboutGlobalSHANGHAIBody02": "これからの成長する中国ビジネスの拠点として、上海を中心にモノづくり産業の省人化に貢献して参ります。",
    "AboutGlobalButtun": "会社ホームページへ",
    "AboutGlobalListTitle": "提携企業一覧",
    "AboutGlobalListBody": "様々なニーズに合わせた製品開発に対応するために、<br class='pc-only'/>海外・国外含めて120企業以上の連携ネットワークを持ちます。",
    "AboutGlobalListBase": "海外拠点",
    "AboutGlobalListAgency": "海外代理店",
    "AboutAccessTitle": "事業所・アクセス",
    "AboutAccessSatakeTitle": "佐竹製作所",
    "AboutAccessSatakeBody01": "本社（プロジェクト開発事業）",
    "AboutAccessSatakeBody02": "総務部・事業開発部",
    "AboutAccessSatakeBody03": "〒101-0041<br>東京都千代田区神田須田町1-24-3<br>\nフォーキャストビル7F<br>\nTEL：03-3254-3121<br>\nTEL：03-5830-7505(FA事業)<br>\nFAX：03-3254-3122",
    "AboutAccessSatakeBody04": "カスタム部品事業",
    "AboutAccessSatakeBody05": "草加営業所",
    "AboutAccessSatakeBody06": "〒340-0033<br>埼玉県草加市柳島町257-1<br>TEL：048-928-8751<br>FAX：048-924-2981",
    "AboutAccessSatakeBody07": "山形工場（FA部品事業）",
    "AboutAccessSatakeBody08": "MI事業部",
    "AboutAccessSatakeBody09": "〒999-0605<br>山形県西置賜郡飯豊町添川3514-79<br>東山工業団地<br>TEL：0238-72-3511<br>FAX：0238-72-3521",
    "AboutAccessSankoBody01": "三興工業",
    "AboutAccessSankoBody02": "〒101-0041<br>東京都千代田区神田須田町1-24-3<br>フォーキャストビル2F<br>TEL：03-3526-2860（代表）<br>FAX：03-3525-8059",
    "AboutAccessButton": "会社ホームページへ",
    "AboutAccessTouchBody01": "タッチエンス",
    "AboutAccessTouchBody02": "タッチエンス(関連会社)",
    "AboutAccessTouchBody03": "〒110-0014<br>東京都台東区北上野2-21-10<br>TEL：03-3847-9551（代表）<br>FAX：03-3847-9552",
    "AboutAccessSHANGHAIBody01": "上海宗雄貿易有限公司",
    "AboutAccessSHANGHAIBody02": "上海市長寧区中山西路555号<br>緑洲大厦1幢1楼17単元<br>TEL：86 21 3360 6637<br>FAX：86 21 3360 6639",
    "AboutProfileTitle": "企業概要",
    "AboutProfileHeadline01": "会社名",
    "AboutProfileBody01": "株式会社 佐竹製作所<br>SATAKE Precision Technology Co., Ltd",
    "AboutProfileHeadline02": "代表者",
    "AboutProfileBody02": "尾方 謙一",
    "AboutProfileHeadline03": "お問い合わせ",
    "AboutProfileBody03": "［電話番号］<br>電話対応時間 8:30-17:30<br>・金属加工について　048-928-8751<br>・センサについて　03-3847-9551<br>・継手について　03-3526-2860<br>［メールアドレス］<br>eigyo@satake-s.co.jp",
    "AboutProfileHeadline04": "営業日・<br class='sp-only'/>休業日",
    "AboutProfileBody04": "営業日：月-金<br>休業日：土日・祝日",
    "AboutProfileHeadline05": "営業対応地域",
    "AboutProfileBody05": "全国",
    "AboutProfileHeadline06a": "本社・<br class='sp-only'/>事業開発部",
    "AboutProfileBody06a": "〒101-0041<br>東京都千代田区神田須田町1-24-3<br>\nフォーキャストビル7F<br>\nTEL：03-3254-3121<br>\nTEL:03-5830-7505(FA事業課)<br>\nFAX：03-3254-3122",
    "AboutProfileHeadline06b": "CMW事業部",
    "AboutProfileBody06b": "〒340-0033<br>埼玉県草加市柳島町257-1番地<br>TEL：048-928-8751<br>FAX：048-924-2981",
    "AboutProfileHeadline06c": "MI事業部",
    "AboutProfileBody06c": "〒999-0605<br>山形県西置賜郡飯豊町添川 東山工業団地<br>TEL：0238-72-3511<br>FAX：0238-72-3521",
    "AboutProfileHeadline06d": "センサ事業部<br>（タッチエンス）<br>（関連会社）",
    "AboutProfileBody06d": "〒110-0014<br>東京都台東区北上野2-21-10<br>TEL：03-3847-9551<br>FAX：03-3847-9552",
    "AboutProfileHeadline06e": "JSK事業部<br>（三興工業）",
    "AboutProfileBody06e": "〒101-0041<br>東京都千代田区神田須田町1-24-3<br>フォーキャストビル2F<br>TEL：03-3526-2860<br>FAX：03-3525-8059",
    "AboutProfileHeadline07": "資本金",
    "AboutProfileBody07": "50,000千円",
    "AboutProfileHeadline08": "社員数",
    "AboutProfileBody08": "208名",
    "AboutProfileHeadline09": "取り扱い商品",
    "AboutProfileBody09": "1.ネジの製造および販売<br>2.精密機械部品の製造および販売<br>3.医療機器、医療機器部品の製造および販売<br>4.精密治工具の製造および販売<br>5.触覚センサの開発・製造および販売",
    "AboutProfileHeadline10": "主要取引先",
    "AboutProfileBody10": "［メカニカル部品、ネジ関連］<br>各制御機器メーカー・機械設備メーカー<br>自動車部品メーカー・医療機器メーカー<br>飲料プラントメーカー等",
    "ContactTitle": "お問い合わせ",
    "ContactHeadline01": "佐竹製作所の製品はセミオーダーからフルオーダーまで、もちろん既製品も、スピーディーに納品が可能です。<br>お仕事のご相談は、お電話・FAX・メール・インターネットで受け付けております。まずは、お気軽にお問い合わせください。",
    "ContactPrivacy": "プライバシーポリシーについて",
    "ContactMainNumber": "048-928-8751",
    "ContactMainAdrress": "受付時間 / 平日9:00 - 18:00 （土日祝日を除く）<br>FAX / 048-924-2981<br>メール / eigyo@satake-s.co.jp",
    "ContactHeadline02": "お問い合わせ内容がお決まりの場合は以下に直接ご連絡ください。",
    "ContactMetal01": "金属加工について",
    "ContactMetal02": "佐竹製作所<br>電話番号 / 048-928-8751<br>FAX番号 / 048-924-2981",
    "ContactFittings01": "継手について",
    "ContactFittings02": "三興工業<br>電話番号 / 03-3526-2860<br>FAX番号 / 03-3525-8059",
    "ContactSensor01": "センサについて",
    "ContactSensor02": "タッチエンス(関連会社)<br>電話番号 / 03-3847-9551<br>FAX番号 / 03-3847-9552",
    "ContactSitesTitle": "各営業所へのお問い合わせ",
    "ContactSites01": "本社",
    "ContactSites01Number": "電話番号 / 03-3254-3121<br>FAX番号/ 03-3254-3122",
    "ContactSites02": "草加営業所",
    "ContactSites02Number": "電話番号 / 048-928-8751<br>FAX番号 / 048-924-2981",
    "ContactSites03": "山形工場",
    "ContactSites03Number": "電話番号 / 0238-72-3511<br>FAX番号 / 0238-72-3521",
    "ContactSites04": "三興工業",
    "ContactSites04Number": "電話番号 / 03-3526-2860<br>FAX番号 / 03-3525-8059",
    "ContactSites05": "タッチエンス(関連会社)",
    "ContactSites05Number": "電話番号 / 03-3847-9551<br>FAX番号 / 03-3847-9552",
    "ContactSites06": "上海宗雄貿易有限公司",
    "ContactSites06Number": "電話番号 / 010-86-21-3360-6637",
    "ContactFormTitle": "お問い合わせフォーム",
    "ContactForm01": "お名前",
    "ContactForm02": "会社名",
    "ContactForm03": "メールアドレス",
    "ContactForm04": "題名",
    "ContactForm05": "内容",
    "ContactForm06": "入力内容を確認する",
    "ContactFormButton1": "修正する",
    "ContactFormButton2": "送信する",
    "ContactFormError01": "名前が未入力です",
    "ContactFormError02": "会社名が未入力です",
    "ContactFormError03": "メールアドレスが未入力です",
    "ContactFormError04": "題名が未入力です",
    "ContactFormError05": "内容が未入力です",
    "ContactFormError06": "エラーが発生しました。再度送信をしてください。",
    "ContactFormSub01": "送信完了",
    "ContactFormSub02": "送信完了致しました。<br>担当者よりご返信いたしますので少々お待ちください。",
    "OnlineStoneTitle": "オンラインストア",
    "OnlineStoneJSK": "JSKブランドの継手製品を販売するオンラインショップです。<br class='pc-only'/>即日納品。どこよりも早くお届けします。",
    "OnlineStoneJSKButton": "JSK オンラインショップへ",
    "OnlineStoneSPS": "佐竹グループの製品を取り扱う<br class='sp-only'/>オンラインショップです。<br>特殊なセンサなどを1つから販売しております。",
    "OnlineStoneSPSButton": "SPS オンラインショップへ",
    "PrivacypolicySub": "プライバシーポリシー",
    "PrivacypolicyTitle": "個人情報の取扱い",
    "PrivacypolicyHeadline01": "・はじめに",
    "PrivacypolicyBody01": "この文書は、当社ホームページを使いお問合わせされる方の、個人情報の保護とお取扱いについて、<br>個人情報保護の定めに従いご説明するものです。",
    "PrivacypolicyHeadline02": "・当社の基本姿勢",
    "PrivacypolicyBody02": "当社は、個人情報の保護を確実にいたします。 当社はお問い合せいただいた方の個人情報を、同意をいただいた上で入手いたします。<br>当社は従業員に対して継続的に個人情報保護教育を行い、ご本人の個人情報を厳重に管理いたします。",
    "PrivacypolicyHeadline03": "・個人情報の利用目的",
    "PrivacypolicyBody03": "お問い合せに関しての個人情報は、問い合わせに対する回答及び問合せに関わる処理のためのみに利用します。",
    "PrivacypolicyHeadline04": "・提供及び委託",
    "PrivacypolicyBody04": "当社は、お問い合せいただいた方の個人情報を法令に基づき、裁判所、警察機関等の公的機関からの要請があった場合については、<br>当該公的機関に提供することがあります。",
    "PrivacypolicyHeadline05": "・開示、苦情、訂正、削除、利用停止等の申立先",
    "PrivacypolicyBody05": "ご提供いただきましたお問い合せいただいた方の個人情報は、利用目的の通知、開示及び情報の訂正・削除、利用停止等を請求することができます。<br>開示、訂正・削除等を請求される場合は、下記までご連絡下さい。<br>その場合、お問い合せいただいた方以外への個人情報の漏洩等を防止するため、お問い合せいただいた方であることの確認をさせていただいたうえ、<br>速やかに開示、訂正・削除、利用停止等の措置をとらせていただきます。<br>なお、法令及び個人情報保護マネジメントシステムにより、請求に応ずることができない場合は、その理由を遅滞なく通知いたします。",
    "PrivacypolicyBody05a": "①個人情報管理責任者：総務部総務課長<br>②苦情窓口：総務部",
    "PrivacypolicyBody05b": "個人情報お問い合わせ窓口<br>電話：03-3254-3121<br>E-Mail：soumu@satake-s.co.jp　",
    "PrivacypolicyHeadline06": "・提供の任意性と結果",
    "PrivacypolicyBody06": "また、個人情報を提供する/しないはお問い合せいただいた方の自由ではありますが、<br>提供しない場合は、正確な回答及び関連の処理ができない場合がある事をご承知下さい。",
    "PrivacypolicyHeadline07": "・お問い合せいただいた方が容易に認識できない方法で取得する場合",
    "PrivacypolicyBody07": "当社は、お問い合せいただいた方からは容易に認識できない方法での取得は行いません。",
    "PrivacypolicyHeadline08": "・個人情報の廃棄・消去",
    "PrivacypolicyBody08": "お問い合せいただいた方からお預かりした個人情報は、当社からの回答及び問合せに関わる処理後、<br>お問い合せいただいた方の事前の承諾を得ることなく、安全かつ完全に廃棄または消去いたします。",
    "FooterContactTitle": "お問い合わせ",
    "FooterContactBody": "佐竹製作所の製品はFA部品からカスタム部品まで、もちろん既製品も、スピーディーに納品が可能です。<br>お仕事のご相談は、お電話・FAX・<br class='sp-only'/>メール・インターネットで受け付けております。<br class='sp-only'/>まずは、お気軽にお問い合わせください。",
    "FooterContactTel": "048-928-8751",
    "FooterContactInfo": "受付時間 / 平日9:00 - 18:00 （土日祝日を除く）<br class='sp-only'/>FAX / 048-924-2981　<br class='sp-only'/>メール / eigyo@satake-s.co.jp",
    "FooterContactButton": "お見積りフォームへ",
    "FooterNews": "ニュース",
    "FooterWorks": "佐竹の事業",
    "FooterMetal": "金属加工事業",
    "FooterFA": "FA事業",
    "FooterFittings": "継手事業",
    "FooterSensor": "センサ事業",
    "FooterAbout": "会社情報",
    "FooterMessage": "代表メッセージ",
    "FooterSatake": "佐竹について",
    "FooterNetwork": "グローバルネットワーク",
    "FooterHistory": "沿革",
    "FooterAccess": "事業所 / アクセス",
    "FooterProfile": "企業概要",
    "FooterContact": "お問い合わせ",
    "FooterShop": "オンラインショップ",
    "FooterJSK": "JSK ONLINE STORE",
    "FooterSPS": "S.P.S",
    "FooterPolicy": "プライバシーポリシー"
},
  "en": {
  "topMainVisualSub": "Continually taking on challenges<br>using our solid technical skills",
    "topNewsSub": "",
    "Button_A": "More",
    "Button_B": "Learn more",
    "topWorksSub": "SATAKE's Business",
    "topWorksHeadline": "SATAKE Precision Technology Co., Ltd. is a global company that is creating the future.",
    "topWorksBody": "The SATAKE Precision Technology Group is a next-generation solution company led by the unique technologies and proposal capabilities it has developed through its experience with metal component processing.It meets customer needs and continually proposes innovative technologies.It develops SATAKE brand products that leverage tactile sensors, designs robotics that help address the problems created by population shrinkage, and improves the value of the \"SATAKE Brand\" as an engineering trading company that provides proposals to customers.",
    "topWorksMetalHeadline": "Metal Processing Business",
    "topWorksMetalBody": "We handle custom-made products, from prototypes to mass-produced products.Based on our precision component processing technologies, we use our own domestic and overseas networks to process custom products.We create and provide the added value that customers truly need, from high-mix low-volume production and prototypes to mass-produced products.",
    "topWorksFAHeadline": "FA Business",
    "topWorksFABody": "We aim to be a company that provides factory automation proposals, using robot systems to improve productivity and add new services that we can propose to customers.We strive to be an engineering trading company that proposes methods for personnel saving and automation to take on the problem of personnel shortages.",
    "topWorksFittHeadline": "Fitting Business",
    "topWorksFittBody": "We develop and manufacture products in the JSK brand, one of the world's top fitting brands. We offer stable product supply and rapid turnaround.Sanko Kogyo Co., Ltd., is a member of the SATAKE Precision Technology Group whose special gas fittings for semiconductor devices are known for having some of the highest levels of quality. Its fittings and gaskets are developed and manufactured in an in-house factory with a clean room.",
    "topWorksSensorHeadline": "Sensor Business",
    "topWorksSensorBody": "We develop, manufacture, and sell innovative tactile sensors that produce advances in the interfaces between robots and people.We collaborated with University of Tokyo to develop original sensors.We then spun off our sensor business into its own company, our affiliate company Touchence Inc. Touchence's highly-experienced engineers support the development of new products for customers.",
    "topAboutSub": "Corporate Data",
    "topAboutHeadline": "We meet diverse needs and support global manufacturing through our high levels of quality.",
    "topAboutBody": "We maintain a strong customer focus and provide solutions as only we can.The SATAKE Group uses the reliable quality of its in-house factory and its wide network of collaborating manufacturers, promising the best coordination and the ultimate in support.",
    "topAboutMessageTitle": "CEO Message",
    "topAboutMessageBody": "We stay abreast of changes in the industrial structure and evolutions in manufacturing as we build the businesses that will support the next generation.",
    "topAboutNetworkTitle": "Global Network",
    "topAboutNetworkBody": "As an FA robot system integrator, we have laid the groundwork for the sale of SATAKE brand devices.We possess the functions necessary to design and develop automation and robotic devices.",
    "": "",
    "NewsNext": "Next",
    "NewsPrev": "Prev",
    "WorksTopTitle": "SATAKE's Business",
    "WorksTopHeadline": "SATAKE Precision Technology Co., Ltd. is a global company that is creating the future.",
    "WorksTopBody": "The SATAKE Precision Technology Group is a next-generation solution company led by the unique technologies and proposal capabilities it has developed through its experience with metal component processing.It meets customer needs and continually proposes innovative technologies.It develops SATAKE brand products that leverage tactile sensors, designs robotics that help address the problems created by population shrinkage, and improves the value of the \"SATAKE Brand\" as an engineering trading company that provides proposals to customers.",
    "worksMetalTitle": "Metal processing business",
    "worksMetalBody": "We handle custom-made products, from prototypes to mass-produced products. Based on our precision component processing technologies, we use our own domestic and overseas networks to process custom products.       We create and provide the added value that customers truly need, from high-mix low-volume production and prototypes to mass-produced products.",
    "worksFullorderTitle": "Custom component proposal, manufacturing, and mass production",
    "worksFullorderBody": "Our fully made-to-order production specializes in turning any customer request into reality.  We provide full support for everything from design to product commercialization and quality management.",
    "worksSemiorderTitle": "FA component manufacturing in our in-house factory",
    "worksSemiorderBody": "We handle high-mix low-volume production of FA components with short lead times.We focus on speed in order to improve quality.",
    "worksFATitle": "FA Business",
    "worksFABody": "We aim to be a company that provides factory automation proposals, using robot systems to improve productivity and add new services that we can propose to customers.We strive to be an engineering trading company that proposes methods for personnel saving and automation to take on the problem of personnel shortages.",
    "worksFittingsTitle": "Fitting Business",
    "worksFittingsBody": "We develop and manufacture products in the JSK brand, one of the world's top fitting brands. We offer stable product supply and rapid turnaround.Sanko Kogyo Co., Ltd., is a member of the SATAKE Precision Technology Group whose special gas fittings for semiconductor devices are known for having some of the highest levels of quality. Its fittings and gaskets are developed and manufactured in an in-house factory with a clean room.",
    "worksSensorTitle": "Sensor Business",
    "worksSensorBody\n": "We develop, manufacture, and sell innovative tactile sensors that produce advances in the interfaces between robots and people.We collaborated with University of Tokyo to develop original sensors. We then spun off our sensor business into its own company, our affiliate company Touchence Inc. Touchence's highly-experienced engineers support the development of new products for customers.",
    "MetalTopTitle": "Metal Working",
    "MetalTopHeadline": "SATAKE's metal processing handles custom-made products, from prototypes to mass-produced products.",
    "MetalTopBody": "Our custom metal works division, which specializes in custom production, and our FA component division, which uses a semi-custom approach to achieve greater speed, enables us to optimally meet our customers' diverse needs.",
    "MetalTopCustomBody": "Our fully made-to-order production specializes in turning any customer request into reality. We provide full support for everything from design to product commercialization and quality management.",
    "MetalTopFATitle": "FA component division",
    "MetalTopFABody": "We handle high-mix low-volume production of FA components with short lead times. We focus on speed in order to improve quality.",
    "CustomTitle": "Custom Metal Works Division",
    "CustomHeadline": "We can fulfil any order.",
    "CustomBody": "We offer fully customized component development to meet our customers' needs.<br>\nWe offer unified support for optimized product proposal, <br class='pc-only'/>\nmanufacturing, and mass production.<br>\nConsult with us about anything from detailed design diagrams to ideas<br class='pc-only'/>\nstill in their incipient stages.<br>\nWe collaborate with over 100 specialized manufacturers to <br class='pc-only'/>\nprovide wide-ranging support from improvement proposals for increasing <br class='pc-only'/>\nefficiency to the development of products which require advanced technologies.",
    "C_SatakeQuality01Tilte": "Creating high precision products is a matter of course for SATAKE.We provide ideas that go above and beyond mere precision.",
    "C_SatakeQuality01Body": "It's important to develop products that require high precision technologies, but efficiency, such as lead time reductions, is also extremely important.We use our long years of experience to provide optimal proposals.",
    "C_SatakeQuality02Tilte": "We collaborate with over 200 manufacturers.We can handle your advanced technical needs.",
    "C_SatakeQuality02Body": "SATAKE uses its technologies and expertise in its in-house factory, but has also built a collaborative system with over 200 dedicated manufacturers with their own individual technical capabilities.Our collaborative network enables us to provide a wide range of proposals.",
    "C_SatakeQuality03Tilte": "State-of-the-art inspection equipment and database creation.Our quality assurance system earns the trust of our customers.",
    "C_SatakeQuality03Body": "In order to manage the diverse orders we receive from our customers, we actively use new technologies, such as state-of-the-art inspection devices and databases. These enable us to make constant improvements and maintain an even higher level of quality.",
    "C_SatakeQualityAssurance": "SATAKE's Quality Assurance",
    "C_Assurance01Title": "01. Database of all products created using barcode system",
    "C_Assurance01Body": "SATAKE Precision Technology uses a database that leverages the barcode system it developed in-house. This database is used to manage quality and shipping for over 30,000 processed metal components, and makes it possible for us to offer ultra-short lead times of as little as one day.",
    "C_Assurance02Title": "02. Thorough confirmation using state-of-the-art inspection devices",
    "C_Assurance02Body": "SATAKE Precision Technology's Quality Assurance Division leads inspections during each step of the manufacturing process, from material receiving to packaging and shipping. These inspections are performed using general measuring devices and state-of-the-art inspection devices. We inspect our products closely, managing their quality systematically, with the aim of producing zero defects. This guarantees the high quality of our products.",
    "C_Assurance03Title": "03. Quality management system",
    "C_Assurance03Body": "SATAKE Precision Technology has defined a quality policy aimed at improving customer satisfaction, and all business sites have received ISO9001 certification (ISO9001 is an international quality management standard).  We will continue to make ongoing improvements and strive to provide a steady and rich selection of superior products and services. We have also obtained quality and environmental ISO certification. Our goal is not merely to obtain certification, but to fully integrate our management systems to provide greater value.",
    "C_ISO9001": "ISO9001",
    "C_ISO9001Date01": "May 1997  ",
    "C_ISO9001Body01": "Yamagata Manufacturing Division obtained ISO9001 certification (JQA-1738)",
    "C_ISO9001Date02": "October 2003  ",
    "C_ISO9001Body02": "Yamagata Manufacturing Division passed ISO9001:2000 upgrade screening",
    "C_ISO9001Date03": "May 2006  ",
    "C_ISO9001Body03": "All company sites obtained ISO9001 certification",
    "C_ISO14001": "ISO14001",
    "C_ISO14001Date01": "December 2006",
    "C_ISO14001Body01": "Obtained ISO14001 certification (JQA-EM5640)",
    "C_ISO9001PDF": "ISO9001 Certificate and Appendix",
    "C_ISO14001PDF": "ISO14001 Certificate and Appendix",
    "C_ExamplesOfProposals": "Examples of proposals",
    "C_ExamplesOfProposalsBody": "Through application of the fully order-made metal component processing that is the specialty of SATAKE Precision Technology,<br class='pc-only'/>\nwe have proactively resolved the problems of our customers.<br>\nSome examples of proposals that have realized “giving concrete form to concepts” are set out here.",
    "C_Examples01Title": "Cutting processing",
    "C_Examples01Body": "We have provided our customers with cold forging and cutting proposals to successfully reduce costs by roughly 30%. Processing blanks using cold forging greatly reduces material and cutting costs. This processing method is best suited for products with some degree of volume that are thick along their axis.",
    "C_Examples02Title": "Design",
    "C_Examples02Body": "When combining cutting plates and press pins, we designed and proposed our own optimal press pin size and used it to produce finished products. We worked together with customers to consider quality, delivery times, and costs from the product prototype rough drawing and sketch stage, provided manufacturing design support, and greatly reduced design lead time.",
    "C_Examples03Title": "Processing of difficult shapes",
    "C_Examples03Body": "The existing technologies used by the customer were difficult and involved significant loss. We collaborated with a partner plant with optimal welding technologies to provide a one-stop solution. The surfaces of the completed articles were sensitive, so we also designed and proposed packaging which would protect them from damage.",
    "C_Examples04Title": "Spinning lathe processing",
    "C_Examples04Body": "The customer wanted to smoothly handle the transition from prototyping to mass production, so we proposed the use of spinning for prototyping pressed products. Spinning can be ordered on an individual product basis, so it's perfect for spot use for small lots by customers concerned about the cost of making dies for pressing products.",
    "C_Examples05Title": "Wire cutting processing",
    "C_Examples05Body": "Working in collaboration with a specialist manufacturer, SATAKE Precision Technology runs more than 12 wire cutting machines for 20 hours every day to realize major cuts in hourly costs. This approach makes it possible to handle thicknesses of 0.01 ～ 300 mm and to carry out stack processing of thin plates. Our facility is fully equipped with approximately 250 jigs including special shapes to realize cost reductions.",
    "C_Examples06Title": "Lost wax processing",
    "C_Examples06Body": "SATAKE Precision Technology's lost-wax process uses overseas production to offer lower costs than domestic manufacturing while maintaining the same quality as domestically manufactured products. Compared to domestic manufacturing, lost-wax processing cuts material costs by roughly 30% and mold costs by roughly 65% -- significant savings.",
    "C_Examples07Title": "Transfer press processing",
    "C_Examples07Body": "We provide proposals for switching from a multi-process approach consisting of single-shot pressing and assembly to integrated pressing technology to meet customer needs. Our large progressive press machines can process stainless steel sheets up to 9.0mm thick, reducing costs by roughly 30% as well as shortening lead time.",
    "FAComponentDivisionTitle": "FA component division",
    "FAComponentDivisionHeadline": "Growing ever faster as we aim to be the fastest<br class='pc-only'/>\nin the industry.",
    "FAComponentDivisionBody": "Our FA component division uses an integrated production approach<br class='pc-only'/>\nin our in-house factory to increase production speed and lower costs. <br>\nHow can be provide products to customers even more quickly?<br>\nThat's what's on our minds every day.Our factory operates 24 hours a day, <br class='pc-only'/>\nwe make improvements to our working environment, <br class='pc-only'/>\nand we use ideas from the field to implement further improvements.<br>\nAs a result, we are able to ship products in as few as<br class='pc-only'/>\nfour hours after order placement.We will continue to make improvements<br class='pc-only'/>\nto reduce this lead time even further.",
    "F_SatakeQuality01Tilte": "The same lead times, even for products involving numerous processes",
    "F_SatakeQuality01Body": "We offer the same lead times, even for production that involves cutting, press lathe working, heat treatment, surface treatment, and other processes.We offer over 30,000 types of products, including products of different sizes.",
    "F_SatakeQuality02Tilte": "Ultra-small lot production.<br class='pc-only'/>Same-day shipment of orders as small as a single screw",
    "F_SatakeQuality02Body": "We offer ultra-small lot production, with same-day shipment of orders as small as a single screw.<br class='sp-only'/>Of course, we also offer same-day shipment for large orders as well.",
    "F_SatakeQuality03Tilte": "We make improvements 24 hours a day, 365 days a year to provide you with ultra-short lead times",
    "F_SatakeQuality03Body": "We are constantly making improvements to speed up production and provide you with ultra-short lead times.Our factory operates 24 hours a day, we make introduce state-of-the-art equipment, and we use ideas from the field to implement further improvements.The numerous small improvements we make enable us to provide shorter turnaround times.",
    "F_FourHoursTitle": "From order placement to shipping in as little as four hours!",
    "F_ProcessTitle": "Examples of our diverse processing technologies",
    "F_Process01Title": "Lathes machines",
    "F_Process01Body": "we have 40 NC Lathes machines in Yamagata facility.NC Lathes-attached with a multi-axis machining device can create any product shape with excellent precision.",
    "F_Process02Title": "Heat treatment",
    "F_Process02Body": "Our in-house factory has salt baths with short heat treatment times, enabling us to manufacture small lots with short lead times.",
    "F_Process03Title": "Polishing",
    "F_Process03Body": "Our cylindrical polishing equipment can achieve external tolerances on the micron level. It produces a surface roughness of 0.8a or less.",
    "F_Process04Title": "Machining centers",
    "F_Process04Body": "Our machining centers cover both vertical and horizontal machining and can perform machining for two- and three-dimensional workpieces in short amounts of time.",
    "F_Process05Title": "Welding",
    "F_Process05Body": "We have multiple TIG welders to perform welding for a large variety of articles with short lead times.",
    "F_Process06Title": "Surface treatment",
    "F_Process06Body": "We have dedicated tanks for surface treatment, including electroless nickel, trivalent chromate, and zinc plating.",
    "F_Process07Title": "3D measurement equipment",
    "F_Process07Body": "We manage quality using state-of-the-art 3D measurement devices with AI functions.",
    "F_Process08Title": "Database",
    "F_Process08Body": "We use a database to perform one piece manufacturing of any of roughly 30,000 semi-custom products.",
    "F_Process09Title": "Composition analysis",
    "F_Process09Body": "We perform analysis to check that the properties of metal materials are good fits for specifications, and that the amounts of substances to which environmental restrictions apply are under restriction limits.",
    "FABusinessTitle": "FA business",
    "FABusinessHeadline": "We develop in-house FA systems as<br class='pc-only'/>an FA system integrator that contributes<br class='pc-only'/>to the next generation.",
    "FABusinessBody": "Improving productivity is an important business challenge for small<br class='pc-only'/>\nand medium-sized enterprises.<br>\nSATAKE Precision Technology strives to be an engineering company<br class='pc-only'/>\nthat can provide proposals for improving productivity<br class='pc-only'/>\nthrough labor-saving and automation.<br>\nSATAKE Precision Technology began as a component manufacturer.<br>\nAs a small company that strives to improve the future of manufacturing,<br>\nwe develop FA systems that offer exceptional cost performance.<br>\nWe aim not only to improve efficiency by introducing them in in-house factories,<br class='pc-only'/>\nbut also to perform verification and improvements through actual implementation,<br class='pc-only'/>\nso our FA systems are always evolving.<br>\nWe will continue with our development work, commercializing and<br class='pc-only'/>\nselling FA systems used in future smart factories to further support the evolution<br class='pc-only'/>\nof the manufacturing industry.",
    "FABusinessButtonLabel": "Satake new FA website",
    "FABusinessAboutTitle": "About SATAKE Precision Technology's FA business",
    "FABusinessAbout01Title": "Component manufacturing",
    "FABusinessAbout01Body": "Our FA division promote the introduction of labor-saving and automation by performing in-house factory site analysis and using technologies such as the IoT, robots, and RPA. We provide solutions optimized for use in the field.",
    "FABusinessAbout02Title": "FA equipment development",
    "FABusinessAbout02Body": "Our MI division, which operates our in-house factories, uses provided solutions. Feedback from the field based on actual usage is relayed to the FA division, and all members of the division work together as one to improve efficiency.",
    "FABusinessAbout03Title": "FA equipment sales",
    "FABusinessAbout03Body": "Solutions backed by extensive experience provide functions needed in the manufacturing field. Solution proposals support the transformation of factories into smart factories, from the ground up.",
    "FABusinessFutureTitle": "The future horizons of SATAKE Precision Technology being opened up through our FA business",
    "FABusinessFuture01Title": "We meet the diverse needs of our customers.",
    "FABusinessFuture02Headline": "Expansion of current business",
    "FABusinessFuture02Body": "・Provision of broad ranges of products<br>・Support for modularization",
    "FABusinessFuture03Headline": "Diverse solutions",
    "FABusinessFuture03Body": "・FA device customization<br>・Grippers with advanced sensors<br>・Smart platforms",
    "FABusinessFuture04Title": "We are active in next-generation growth fields, expanding our business.",
    "FABusinessFuture05Headline": "IoT technology development",
    "FABusinessFuture05Body": "・ IoT basic modules and applications<br>・Sensing technologies (movement of machines, articles, and people)",
    "FABusinessFuture06Headline": "Fusion with automation and labor-saving devices",
    "FABusinessFuture06Body": "・Development of RPA-based automation and labor-saving devices",
    "FABusinessFuture07Headline": "Meeting the diverse needs of automated production lines",
    "FABusinessFuture07Body": "・Visualization, monitoring, and process analysis",
    "FittingBusinessTitle": "Fitting Business",
    "FittingBusinessHeadline": "Sanko Kogyo is a manufacturer that specializes<br class='pc-only'/>in making the fittings used with ultra-high purity gas,<br class='pc-only'/> chemicals, and ultra-high vacuums.",
    "FittingBusinessBody": "Sanko Kogyo uses the ultraclean technologies it has cultivated for over 25 years to specialize in the manufacturing of fittings for use with ultra-high purity gas, chemicals, and ultra-high vacuums.It has acquired patents around the world for the innovative new structures of its fittings.",
    "FittingBusinessContact": "Contact to Sanko Kogyo",
    "FittingBusinessNumber": " +81-3-3526-2860",
    "FittingBusinessAdrress": "Reception hours: (Monday to Friday: 9 a.m. to 6 p.m. Closed on Saturdays, Sundays, and public holidays)  Fax: +81-3-3525-8059   Email: kanrika@jsk-sanko.co.jp",
    "FittingBusinessButton": "Sanko Kogyo website",
    "SensorBusinessTitle": "Sensor Business",
    "SensorBusinessHeadline": "Touchence is a sensor company that creates future<br class='pc-only'/> of tactile sensitivity science.",
    "SensorBusinessBody": "Products such as highly novel original tactile sensors and sensor modules have won high acclaim on markets for products such as consumer robots, sporting apparatus and nursing devices and contribute to the realization of products never seen before such as input and detection devices.",
    "SensorBusinessContact": "Contact to Touchence",
    "SensorBusinessNumber": " +81-3-3847-9551",
    "SensorBusinessAdrress": "Reception hours: (Monday to Friday: 9 a.m. to 6 p.m. Closed on Saturdays, Sundays, and public holidays)  Fax: +81-3-3847-9552   Email: info@touhchence.jp",
    "SensorBusinessButton": "Touchence website",
    "AboutTopTitle": "Corporate Data",
    "AboutTopHeadline": "We meet diverse needs and support global manufacturing through our high levels of quality.",
    "AboutTopBody": "We maintain a strong customer focus and provide solutions as only we can.The SATAKE Group uses the reliable quality of its in-house factory and its wide network of collaborating manufacturers, promising the best coordination and the ultimate in support.",
    "AboutTop01Title": "CEO Message",
    "AboutTop01Body": "A message from President Kenichi Ogata",
    "AboutTop02Title": "About SATAKE",
    "AboutTop02Body": "Our Corporate Philosophy and Management Policy",
    "AboutTop03Title": "Global Network",
    "AboutTop03Body": "Our overseas partners",
    "AboutTop04Title": "Office, Access",
    "AboutTop04Body": "Information on how to reach our business sites",
    "AboutTop05Title": "History",
    "AboutTop05Body": "The history of SATAKE",
    "AboutTop06Title": "Company Profile",
    "AboutTop06Body": "Basic information about SATAKE",
    "AboutCEOMessageHeadTitle": "",
    "AboutCEOMessageTitle": "President<br>Kenichi Ogata",
    "AboutCEOMessageBody01": "Since 1937, we have provided special bolts and machine components that meet customer needs in a wide variety,with small lots and short delivery times.\n",
    "AboutCEOMessageBody02": "Our company, as a supplier of metal components, has continued to challenge itself in all kinds of ways to respond to the dramatically changing industrial structure and put importance on responding further to our customers’ needs by growing and evolving.\n",
    "AboutCEOMessageBody03": "We Provide solutions for the future by Our Original Technology and services.\n",
    "AboutCEOMessageBody04": "We believe that responding to our customers’ needs means evolving our various businesses with the market, using our past experience in providing special metal components.",
    "AboutCEOMessageBody05": "Since the Lehman Shock, the industrial structure of Japan has changed dramatically. We have given up non-growth businesses, consolidated our custom-made metal components business and expanded new services. We strengthened the FA market business by speedily specializing our existing plants in production speed and set up a Business Development Division to launch new businesses. This new division establishes a Sensor Business aiming for consumer robots market as a next stage in the FA market, and then creates original metal parts for robots in synergy with the existing businesses and expand our business in the new markets … Our company always moves forward.",
    "AboutCEOMessageBody06": "The SATAKE Group currently comprises three companies: a sensor business that provides the world’ s first tactile sensors as a unique technology, Touchence, Inc., and a special fittings business with in-house-developed brand of JSK, Sanko Kogyo Co., Ltd. We are also expanding the handling of brand products from other companies such as resin additives and gas sensors to enhance the line-up that we can offer to customers.\n",
    "AboutCEOMessageBody07": "In addition, since we are expanding overseas offices by focusing in Asia such as China and Thailand, by gradually expanding the providing areas, we will strive to make contribution to production facility industries around the world.\n",
    "AboutCEOMessageBody08": "The custom-made metal processing business also meets customer needs even better than before and will continue to evolve to propose new added value.\n",
    "AboutCEOMessageBody09": "Our company has a young management team and young employees and will continue to further challenge itself in every way. You can expect us to grow and evolve for the sake of our customers.",
    "AboutSatakeTitle": "",
    "AboutSatakeHeadline01": "We enable you to take on new fields and grow.",
    "AboutSatakeBody01": "As a company supported by the precision mechanical component industry, focusing on metal component processing, we meet the needs of our customers. We are continuing to grow and evolve as a partner to our customers. We aren't out to become the number one company in the world, but the number one company for our customers.",
    "AboutSatakeHeadline02": "SATAKE's growing and developing businesses",
    "AboutSatakeProjectTitle": "Project Development",
    "AboutSatakeProjectBody": "We support the enhancement, growth, and evolution of existing businesses. We also develop new projects, get them rolling smoothly, and commercialize them. We provide dependable roll-out support through our business planning, proposal, startup, and brand strategy.We actively engage in overseas expansion and cross-licensing for various business sectors, which are becoming increasingly globalized. We operate overseas business sites and promote local procurement.",
    "AboutSatakeSupportTitle": "Support for the enhancement, growth, and evolution of existing businesses",
    "AboutSatakeSupportBody": "We accurately meet customer needs by evolving business in line with the evolution of individual markets.",
    "AboutSatakeNewTitle": "New business planning, proposal, and brand strategy formulation",
    "AboutSatakeNewBody": "In order to meet the needs of the constantly changing industrial sector, we are constantly taking on the challenges of developing new businesses.",
    "AboutSatakeOverseasTitle": "Overseas expansion and cross-licensing",
    "AboutSatakeOverseasBody": "We are expanding our overseas locations, primarily in Asia, and enriching the lineup of products we supply to customers.",
    "AboutSatakeManaHeadline": "Management goals",
    "AboutSatakeManaBoby01": "1. To become a company that offers enhanced customer satisfaction and values.",
    "AboutSatakeManaBoby02": "2. To give our employees the change to improve their lives and realize self-fulfillment.",
    "AboutSatakeManaBoby03": "3. To contribute society through the continued existence and growth of our company.",
    "AboutSatakeBasicHeadline": "Basic management policy",
    "AboutSatakeBasicBody": "To become the number-one partner for our customers through the efforts of each and every one of our employees to improve themselves and the continued evolution of the values we provide in order to contribute to industrial growth and the improvement of life in the society of tomorrow.",
    "AboutSatakePerHeadline": "Personal principles",
    "AboutSatakePerBody01": "1. Let’s proactively tackle the challenges of development, innovation and improvement to make SATAKE Precision Technology a strong company with a sense of purpose.",
    "AboutSatakePerBody02": "2. Let’s act with speed and sincerity to our customers.",
    "AboutSatakePerBody03": "3. Let’s tackle our work with uncompromising commitment to quality.",
    "AboutSatakePerBody04": "4. Let’s resolve problems by applying the three principles of workplace, product and realization.",
    "AboutSatakePerBody05": "5. Let’s become unrivalled professionals through a process of putting principles into practice and self-enlightenment.",
    "AboutSatakeFutureHeadline": "Future Oriented",
    "AboutSatakeFutureBody": "An evolving creative company.<br>\nAs the times change, so, too, do elements such as the industrial structure and senses of values. Amidst such changes, SATAKE Precision Technology constantly looks ahead to respond flexibly through innovations and system creation matched to the new era. We will continue to boldly tackle the challenges of developing new fields and spheres of business.",
    "AboutSatakeDeveHeadline": "Development Oriented",
    "AboutSatakeDeveBody": "Achievement of unique position through collaboration between industry and academia.<br>\nAs well as its commitment to the field of precision processing, SATAKE Precision Technology has accelerated its development of new technologies by a process of constant fusion of new technologies through undertaking such as making inroads into the field of robot awareness and control technology in collaboration with the University of Tokyo. So we have been tackling the creation of unique products.",
    "AboutSatakeCusHeadline": "Customer Oriented",
    "AboutSatakeCusBody": "Aiming to realize the number-one service in Japan.<br>\nWe deliver the ultimate in service. We accept order for same-day delivery for even only one screw. By streamlining our service system in uncompromising pursuit of high-mix low-volume, short lead time production, it is our aim to become the best partner for our customers.",
    "AboutGlobalTitle": "",
    "AboutGlobalHeadline": "The strengths of our diverse overseas network",
    "AboutGlobalBody": "We coordinate with business sites in countries around the world to provide support on a global scale.As a company supported by the precision mechanical component industry, focusing on metal component processing, we meet the needs of our customers. We are continuing to grow and evolve as a partner to our customers. We aren't out to become the number one company in the world, but the number one company for our customers.",
    "AboutGlobalSHANGHAI": "SHANGHAI ZONGXIONG COMMERCE Co.,LTD",
    "AboutGlobalSHANGHAIBody01": "We have established marketing and sales sites in China and set our sights on the world's largest FA robot market.<br>\nWith our new Shanghai site, we are expanding our business scope.",
    "AboutGlobalSHANGHAIBody02": "We will contribute to labor-saving in the manufacturing industry, especially in the Shanghai area, through this site that addresses the needs of the growing Chinese business market.",
    "AboutGlobalButtun": "homepage",
    "AboutGlobalListTitle": "List of partner companies",
    "AboutGlobalListBody": "We have a collaborative network with over 120 companies, in Japan and abroad,<br class='pc-only'/>\nto develop products to meet a diverse range of needs.",
    "AboutGlobalListBase": "Overseas Base",
    "AboutGlobalListAgency": "Overseas Agency",
    "AboutAccessTitle": "",
    "AboutAccessSatakeTitle": "SATAKE Precision Technology Co., Ltd",
    "AboutAccessSatakeBody01": "Head Office (Project Development Business)",
    "AboutAccessSatakeBody02": "General affairs division ・ Business development division",
    "AboutAccessSatakeBody03": "7F Forecast Bldg, 24-3, 1-chome, Kandasuda-cho, Chiyoda-ku, Tokyo 101-0041 Japan<br>\nPhone：+81-3-3254-3121<br>\nPhone：+81-3-5830-7505 (FA Division)<br>\nFAX：+81-3-3254-3122",
    "AboutAccessSatakeBody04": "Custom Metal Works, Division.",
    "AboutAccessSatakeBody05": "Soka Sales Office",
    "AboutAccessSatakeBody06": "257-1 Yanagishima-cho, Soka City Saitama 340-0033 Japan<br>Phone：+81-48-928-8751<br>FAX：+81-48-924-2981",
    "AboutAccessSatakeBody07": "Yamagata Manufacturing Division",
    "AboutAccessSatakeBody08": "MI Division",
    "AboutAccessSatakeBody09": "Higashiyama industrial estate Oaza Soegawa Iidemachi Nishiokitamagun Yamagata 999-0605 Japan<br>Phone：+81-238-72-3511<br>FAX：+81-238-72-3521",
    "AboutAccessSankoBody01": "Sanko Kogyo Co .,Ltd.",
    "AboutAccessSankoBody02": "Head Office 2F Forecast Bldg., 24-3, 1-chome, Kandasuda-cho, Chiyoda-ku, Tokyo 101-0041 Japan<br>Phone：＋81-3-3526-2860<br>FAX：＋81-3-3525-8059",
    "AboutAccessButton": "homepage",
    "AboutAccessTouchBody01": "Touchence Inc.",
    "AboutAccessTouchBody02": "Touchence Inc. (affiliate company)",
    "AboutAccessTouchBody03": "2-21-10 Kitaueno, Taitoku, Tokyo 110-0014 Japan<br>Phone：+81-3-3847-9551<br>FAX：+81-3-3847-9552",
    "AboutAccessSHANGHAIBody01": "SHANGHAI ZONGXIONG COMMERCE Co.,LTD",
    "AboutAccessSHANGHAIBody02": "Unit 17, 1st floor, Building 1, Oasis Tower<br>555 Zhongshan West Road, Changning Qu, Shanghai<br>Phone：86 21 3360 6637<br>FAX：86 21 3360 6639",
    "AboutProfileTitle": "",
    "AboutProfileHeadline01": "Company name",
    "AboutProfileBody01": "SATAKE Precision Technology Co., Ltd",
    "AboutProfileHeadline02": "CEO",
    "AboutProfileBody02": "Kenichi Ogata",
    "AboutProfileHeadline03": "Inquiry",
    "AboutProfileBody03": "Opening Hours　8:30-17:30<br>\nAbout Metal Components : <br class='sp-only'/>\n+81-48-928-8751<br>\nAbout Electronic Components : <br class='sp-only'/>\n+81-3-3847-9551<br>\nAbout Fittings : <br class='sp-only'/>\n+81-3-3526-2860<br>\nMail : eigyo@satake-s.co.jp",
    "AboutProfileHeadline04": "Business Days・Holidays",
    "AboutProfileBody04": "Business Days：Mon-Fri.<br>Holidays：Sat,Sun, Public Holidays",
    "AboutProfileHeadline05": "Area for business",
    "AboutProfileBody05": "All over the world",
    "AboutProfileHeadline06a": "Head Office,Project Development Business",
    "AboutProfileBody06a": "7F Forecast Bldg, 24-3, 1-chome, Kandasuda-cho, Chiyoda-ku, Tokyo 101-0041 Japan<br>\nPhone：+81-3-3254-3121<br>\nPhone：+81-3-5830-7505 (FA Division)<br>\nFAX：+81-3-3254-3122",
    "AboutProfileHeadline06b": "Custom Metal Works Business",
    "AboutProfileBody06b": "257-1 Yanagishima-cho, Soka City Saitama 340-0033 Japan<br>Phone：+81-48-928-8751<br>FAX：+81-48-924-2981",
    "AboutProfileHeadline06c": "FA Components Business",
    "AboutProfileBody06c": "Higashiyama industrial estate Oaza Soegawa Iidemachi Nishiokitamagun Yamagata 999-0605 Japan<br>Phone：+81-238-72-3511<br>FAX：+81-238-72-3521",
    "AboutProfileHeadline06d": "Sensor Business<br>(Touchence Inc.)(Affiliate company)",
    "AboutProfileBody06d": "2-21-10 Kitaueno, Taitoku, Tokyo 110-0014 Japan<br>Phone：+81-3-3847-9551<br>FAX：+81-3-3847-9552",
    "AboutProfileHeadline06e": "Fitting Business<br>(Sanko Kogyo Co .,Ltd.)",
    "AboutProfileBody06e": "2F Forecast Bldg., 24-3, 1-chome, Kandasuda-cho, Chiyoda-ku, Tokyo 101-0041<br>Phone：＋81-3-3526-2860<br>FAX：＋81-3-3525-8059",
    "AboutProfileHeadline07": "Capital",
    "AboutProfileBody07": "¥ 50 million",
    "AboutProfileHeadline08": "Employee",
    "AboutProfileBody08": "208",
    "AboutProfileHeadline09": "Products",
    "AboutProfileBody09": "1.Manufacture and sale of screws<br>2.Manufacture and sale of precision machine components<br>3.Manufacture and sale of medical equipment and components<br>4.Manufacture and sale of precision jigs and tools<br>5.Dvelopment,manufacture and sale of tactile sensors",
    "AboutProfileHeadline10": "Main Customers",
    "AboutProfileBody10": "[Mechanical components and screws]<br>Control device manufacturers and mechanical equipment manufacturers<br>Automobile component manufacturers and medical device manufacturers<br>Beverage plant manufacturers, etc.",
    "ContactTitle": "",
    "ContactHeadline01": "SATAKE Precision Technology speedily supplies all kinds of products,<br class='pc-only'/>\nfrom semi-custom products to custom products, as well as ready-made products.<br>\nContact us by telephone, fax, email, or our website for business consultation.<br>\nGet in touch with us so that we can see how we can help you.",
    "ContactPrivacy": "Privacy policy",
    "ContactMainNumber": " +81-48-928-8751",
    "ContactMainAdrress": "Reception time/(Mon.-Fri. : 9am to 6pm Sat. Sun. Public Holiday are off)<br>FAX：+81-48-924-2981<br>Mail：eigyo@satake-s.co.jp",
    "ContactHeadline02": "If you have specific questions, contact us directly at one of the numbers below.",
    "ContactMetal01": "About Metal processing ",
    "ContactMetal02": "SATAKE Precision Technology Co., Ltd<br>Phone：+81-48-928-8751<br>FAX：+81-48-924-2981",
    "ContactFittings01": "About Fittings ",
    "ContactFittings02": "Sanko Kogyo Co., Ltd.<br>Phone：＋81-3-3526-2860<br>FAX：＋81-3-3525-8059",
    "ContactSensor01": "About Electronic Components ",
    "ContactSensor02": "Touchence Inc. (affiliate company)<br>Phone：+81-3-3847-9551<br>FAX：+81-3-3847-9552",
    "ContactSitesTitle": "Inquiry information for individual sites",
    "ContactSites01": "Head Office",
    "ContactSites01Number": "Phone：+81-3-3254-3121<br>FAX：+81-3-3254-3122",
    "ContactSites02": "Custom Metal Works, Division.",
    "ContactSites02Number": "Phone：+81-48-928-8751<br>FAX：+81-48-924-2981",
    "ContactSites03": "Yamagata Manufacturing Division.",
    "ContactSites03Number": "Phone：+81-238-72-3511<br>FAX：+81-238-72-3521",
    "ContactSites04": "Sanko Kogyo Co., Ltd.",
    "ContactSites04Number": "Phone：+81-3-3526-2860<br>FAX：+81-3-3525-8059",
    "ContactSites05": "Touchence Inc. (affiliate company)",
    "ContactSites05Number": "Phone：+81-3-3847-9551<br>FAX：+81-3-3847-9552",
    "ContactSites06": "SHANGHAI ZONGXIONG COMMERCE Co.,LTD",
    "ContactSites06Number": "Phone / 010-86-21-3360-6637",
    "ContactFormTitle": "Online form",
    "ContactForm01": "Your Name",
    "ContactForm02": "Company Name",
    "ContactForm03": "Your E-mail",
    "ContactForm04": "Title",
    "ContactForm05": "Details of your inquiry",
    "ContactForm06": "Send inquiry",
    "ContactFormButton1": "Edit",
    "ContactFormButton2": "Send",
    "ContactFormError01": "The Name field is blank",
    "ContactFormError02": "The Company Name field is blank",
    "ContactFormError03": "The Email Address field is blank",
    "ContactFormError04": "The Title field is blank",
    "ContactFormError05": "The Details section is blank",
    "ContactFormError06": "Error.",
    "ContactFormSub01": "Submitted",
    "ContactFormSub02": "Your inquiry has been submitted.<br>Please wait for a response from one of our staff members. Thank you for your patience.",
    "OnlineStoneTitle": "",
    "OnlineStoneJSK": "Online shop for JSK brand fittings.Same-day delivery. No one delivers faster.",
    "OnlineStoneJSKButton": "JSK online shop",
    "OnlineStoneSPS": "Online shop for SATAKE Group products.Products such as special sensors available, with no minimum order size.",
    "OnlineStoneSPSButton": "SPS online shop",
    "PrivacypolicySub": "",
    "PrivacypolicyTitle": "Handling of Personal Information ",
    "PrivacypolicyHeadline01": "・Introduction",
    "PrivacypolicyBody01": "This document explains about the protection and handling of personal information regarding a person making inquiry (hereinafter, “you”, “your”, as the case may be) through the use of the Company’s homepage, in compliance with the provisions of the personal information protection.",
    "PrivacypolicyHeadline02": "Basic Stance of the Company",
    "PrivacypolicyBody02": "The Company ensures the protection of personal information.  The Company will obtain your personal information by first obtaining your consent. \nThe Company will continue to carry out personal information protection education toward employees, and will strictly manage your personal information.",
    "PrivacypolicyHeadline03": "・Use Purpose of Personal Information",
    "PrivacypolicyBody03": "Personal information related to inquiry will only be used to process and respond to inquiry. ",
    "PrivacypolicyHeadline04": "・Providing and Outsource ",
    "PrivacypolicyBody04": "Pursuant to the laws and regulations, the Company may provide your personal information to public organs such as court and police agency if so requested by such public organs.",
    "PrivacypolicyHeadline05": "・Contact Information Regarding Disclosure, Complaint, Correction, Deletion, Use Suspension, etc.",
    "PrivacypolicyBody05": "You may request for notice/disclosure of use purpose, correction/deletion of information, suspension of use, etc., regarding personal information that you have provided to the Company.  \nPlease contact the information below if you request for disclosure/correction/deletion, etc. \nIn such case, to prevent your information from leaking etc. to any third party, we will take prompt measure such as disclosure, correction/deletion, and suspension of use, by first confirming the identity of requesting person. \nFurther, if the Company is unable to respond to your request subject to laws and regulations, and personal information protection management system, the Company will notify you the reason without delay. ",
    "PrivacypolicyBody05a": "① Personal Information Supervisor：Director, General Affairs Department<br>② Complaint Counter：General Affairs Department ",
    "PrivacypolicyBody05b": "Personal Information Inquiry Counter <br>Phone：03-3254-3121<br>E-Mail：soumu@satake-s.co.jp",
    "PrivacypolicyHeadline06": "・Arbitrary Provided Information and Result ",
    "PrivacypolicyBody06": "Further, please understand that although you have the option to decide whether to provide personal information or not, if you decide not to provide it, there may be cases where the Company will not be able to provide accurate response and other related handling measures. ",
    "PrivacypolicyHeadline07": "・Obtainment by Method Where Difficult to Recognize",
    "PrivacypolicyBody07": "The Company will not obtain your personal information by method that makes it difficult for you to recognize. ",
    "PrivacypolicyHeadline08": "・Disposal/Deletion of Personal Information ",
    "PrivacypolicyBody08": "After the Company provides response and other related process regarding the personal information that you provided to us, we will dispose or delete your personal information in a safe and complete manner without obtaining your prior consent.",
    "FooterContactTitle": "Contact",
    "FooterContactBody": "SATAKE Precision Technology speedily supplies all kinds of products, from FA components to custom components, as well as ready-made products.Contact us by telephone, fax, email, or our website for business consultation. Get in touch with us so that we can see how we can help you.",
    "FooterContactTel": " +81-48-928-8751",
    "FooterContactInfo": "Reception hours: (Monday to Friday: 9 a.m. to 6 p.m. Closed on Saturdays, Sundays, and public holidays)  <br>Fax: +81-48-924-2981   <br class='sp-only'/>Email: eigyo@satake-s.co.jp",
    "FooterContactButton": "Quotation form",
    "FooterNews": "News",
    "FooterWorks": "Works",
    "FooterMetal": "Metal",
    "FooterFA": "Factory Automation",
    "FooterFittings": "Fittngs",
    "FooterSensor": "Sensor",
    "FooterAbout": "About",
    "FooterMessage": "CEO Message",
    "FooterSatake": "About Satake",
    "FooterNetwork": "Global Network",
    "FooterHistory": "History",
    "FooterAccess": "Office, Access",
    "FooterProfile": "Company Profile",
    "FooterContact": "Contact",
    "FooterShop": "Online Shop",
    "FooterJSK": "JSK ONLINE STORE",
    "FooterSPS": "S.P.S",
    "FooterPolicy": "Privacy Policy"
}
}
